version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  wordie:
    build: .
    container_name: wordie
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      # add API_TOKEN
      - REDIS_HOST=redis
      - REDIS_PORT=6379
